# Copyright (C) 2020 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
#  CONTENT
#    simple Makefile to build all source for GdbManipulator
#
#  AUTHOR
#     Sebastian Balz  based on Norbert Stoeffler version
#
#  DATE
#    2018-07-28
#
#  LANGUAGE
#    make
#

APP =		eUnitSelfTest
APP_SRCS =	 main.c  ../eUnit.c  src/byteComp.c  src/cleanBuffer.c  src/justResults.c  src/JustSuccess.c  src/justTestNames.c   src/optOutTests.c  src/shallNotFail.c  src/TestLines.c

APP_INCS =	../
APP_SLIB =	cunit

include		linux.mk
