# Copyright (C) 2020 Intel Corporation
# SPDX-License-Identifier: AGPL-3.0-or-later
#
#  CONTENT
#    simple Makefile to build all source for GdbManipulator
#
#  AUTHOR
#     Sebastian Balz  based on Norbert Stoeffler version
#
#  DATE
#    2018-07-28
#
#  LANGUAGE
#    make
#

APP =		eUnitSelfTest
APP_SRCS =	 main.cpp  
APP_SLIB =	gtest pthread

include		linux.mk
